### ISSUE TITLE
Processes die with large list

### ISSUE THREAD

**Issue by richrumble** [DarkCoderSc/win-brute-logon#2]
C:\>WinBruteLogon.exe -v -u admin -w 10-million-combos.txt     (64-bit btw)
[ .. ] Load 10-million-combos.txt file in memory...
[DONE] 10000001 passwords successfully loaded.
[INFO] 12 cores are available
[ .. ] Create 12 threads...
[INFO] New "TWorker" Thread created with id=17696, handle=520
[INFO] New "TWorker" Thread created with id=12580, handle=524
[INFO] New "TWorker" Thread created with id=14836, handle=536
[INFO] New "TWorker" Thread created with id=20028, handle=532
[INFO] New "TWorker" Thread created with id=11004, handle=576
[INFO] New "TWorker" Thread created with id=12952, handle=580
[INFO] New "TWorker" Thread created with id=24324, handle=612
[INFO] New "TWorker" Thread created with id=7284, handle=624
[INFO] New "TWorker" Thread created with id=17868, handle=636
[INFO] New "TWorker" Thread created with id=5364, handle=648
[INFO] New "TWorker" Thread created with id=1340, handle=660
[INFO] New "TWorker" Thread created with id=10516, handle=672
[DONE] Done.
Progress: 11/10000001 (0%) - 10 password/s, ETA:13:46:39       <---ALL PROCESS DIE
Usage: winbrutelogon.exe -u <username> -w <wordlist_file>
       winbrutelogon.exe -h : Show help.

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Build Type:             Multiprocessor Free
System Manufacturer:       Dell Inc.
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2712 Mhz

https://cloudypirate.com/pjc2dbwb3ycg/10-million-combos.zip.html

**Comment by DarkCoderSc** [comment]
I will take a look. Thank you.

**Comment by DarkCoderSc** [comment]
Can you confirm if the bug is fixed in latest release ?
